import streamlit as st
st.title('How to use the App')
st.markdown("""First, when you open the [application](https://iconicestatemaster.streamlit.app/) it presents you with [1] a dropdown menu containing Lower Super Output Areas (LSOAs) as a list of options. You can either choose the LSOA that corresponds to your area or leave this field blank.""")
# Add developer image
from PIL import Image
image = Image.open('Resources/howto_1.png')
new_image = image.resize((1000, 300))
st.image(new_image)


st.write("Next, you have two predictive options to select from using radio buttons [2]: 'Random Forest' and 'Gradient Boost. After making your choice, click the 'Explore' button [3] to proceed.")

st.write("On the next page, you'll find the 'Area Characteristics' which indicate the domains of deprivation of your selected area. The application displays deprivation domains as sliders that you can adjust. These sliders show the actual domain levels of deprivation for the chosen LSOA. Each slider comes with a helpful tooltip to explain the domain it represents. The sliders are also arranged in the order of the selected models feature importance.")

# Add developer image
from PIL import Image
image = Image.open('Resources/howto_2.png')
new_image = image.resize((500, 500))
st.image(new_image)

st.write("You can modify these sliders to your preferences and then click the 'Predict' button [4] to view the analysis generated by the models.")

